services:
  navigation:
    image: husarion/navigation2:humble-1.1.12-20240123
    network_mode: host
    ipc: host
    volumes:
      - ./config/nav2_params.yaml:/nav2_params.yaml
      - ./maps:/maps
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - POINTCLOUD2_TOPIC=${POINTCLOUD2_TOPIC:-err}
      - SAVE_MAP_PERIOD=${SAVE_MAP_PERIOD-10}
    command: >
      ros2 launch nav2_bringup bringup_launch.py
        slam:=${SLAM:-True}
        params_file:=/nav2_params.yaml
        use_sim_time:=${USE_SIM_TIME:-False}
        map:=/maps/map.yaml
