services:
  navigation:
    image: husarion/navigation2:humble-1.1.16-20240927
    network_mode: host
    ipc: host
    volumes:
      - ./config/nav2_params.yaml:/nav2_params.yaml
      - ./maps:/maps
      - ./husarion_utils:/husarion_utils
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - SAVE_MAP_PERIOD=${SAVE_MAP_PERIOD-10}
    command: >
      ros2 launch /husarion_utils/bringup_launch.py
        namespace:=panther
        point_cloud2_topic:=${POINTCLOUD2_TOPIC:-err}
        map:=/maps/map.yaml
        params_file:=/nav2_params.yaml
        slam:=${SLAM:-True}
        use_sim_time:=${USE_SIM_TIME:-False}
