x-common-config:
  &common-config
  network_mode: host
  ipc: host

services:
  docking:
    # image: husarion/husarion-ugv-navigation:humble-0.1.0-20241113
    build:
      context: ..
      dockerfile: docker/Dockerfile.docking
    container_name: docking
    <<: *common-config
    volumes:
      - ../husarion_ugv_docking:/ros2_ws/src/husarion_ugv_docking
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    command: >
      ros2 launch husarion_ugv_docking docking.launch.py
        namespace:=panther
        use_sim_time:=False
        use_wibotic_info:=False
        camera_color_topic:=/panther/color/image_raw
        camera_color_info_topic:=/panther/color/camera_info
