---
/**:
  pointcloud_crop_box:
    ros__parameters:
      input_topic: <observation_topic>
      output_topic: <observation_topic>_filtered
      target_frame: <namespace>/base_footprint
      min_x: <min_x>
      max_x: <max_x>
      min_y: <min_y>
      max_y: <max_y>
      min_z: <min_z>
      max_z: <max_z>
      negative: true
